<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.aiany</groupId>
    <artifactId>aiany</artifactId>
    <version>0.0.1</version>
    <packaging>pom</packaging>

    <properties>
        <java.version>17</java.version>
        <aiany.version>0.0.1</aiany.version>
        <lombok.version>1.18.30</lombok.version>
        <slf4j-api.version>2.0.16</slf4j-api.version>
        <gson.version>2.10.1</gson.version>
        <bytebuddy.version>1.15.10</bytebuddy.version>
        <opensearch-java.version>2.9.0</opensearch-java.version>
        <jackson.version>2.16.1</jackson.version>
        <github-api.version>1.318</github-api.version>
        <netty.version>4.1.111.Final</netty.version>
        <retrofit.version>2.9.0</retrofit.version>
    </properties>

    <modules>
        <module>aiany-core</module>
        <module>aiany-openai</module>
        <module>aiany-azure</module>
    </modules>


    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.squareup.retrofit2</groupId>
                <artifactId>retrofit</artifactId>
                <version>${retrofit.version}</version>
            </dependency>

            <dependency>
                <groupId>com.squareup.retrofit2</groupId>
                <artifactId>adapter-rxjava2</artifactId>
                <version>${retrofit.version}</version>
            </dependency>

            <dependency>
                <groupId>com.squareup.retrofit2</groupId>
                <artifactId>converter-gson</artifactId>
                <version>${retrofit.version}</version>
            </dependency>

            <dependency>
                <groupId>com.squareup.retrofit2</groupId>
                <artifactId>converter-jackson</artifactId>
                <version>${retrofit.version}</version>
            </dependency>

            <dependency>
                <groupId>com.squareup.okhttp3</groupId>
                <artifactId>logging-interceptor</artifactId>
                <version>3.14.9</version>
            </dependency>

            <dependency>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>${lombok.version}</version>
                <scope>provided</scope>
            </dependency>

            <dependency>
                <groupId>org.slf4j</groupId>
                <artifactId>slf4j-bom</artifactId>
                <version>${slf4j-api.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>com.google.code.gson</groupId>
                <artifactId>gson</artifactId>
                <version>${gson.version}</version>
            </dependency>

            <dependency>
                <groupId>com.fasterxml.jackson</groupId>
                <artifactId>jackson-bom</artifactId>
                <version>${jackson.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <!-- https://github.com/Azure/azure-sdk-for-java -->
            <dependency>
                <groupId>com.azure</groupId>
                <artifactId>azure-ai-openai</artifactId>
                <version>1.0.0-beta.13</version>
            </dependency>


            <!-- region self -->
            <dependency>
                <groupId>com.aiany</groupId>
                <artifactId>aiany-core</artifactId>
                <version>${aiany.version}</version>
            </dependency>

            <dependency>
                <groupId>com.aiany</groupId>
                <artifactId>aiany-openai</artifactId>
                <version>${aiany.version}</version>
            </dependency>


            <!-- endregion -->

        </dependencies>
    </dependencyManagement>


    <repositories>
        <repository>
            <id>aliyun-public</id>
            <url>https://maven.aliyun.com/nexus/content/groups/public/</url>
        </repository>
    </repositories>


</project>